local set = vim.opt

set.spell = false
set.title = true
set.expandtab = true
set.smarttab = true
set.shiftwidth = 2
set.tabstop = 2
set.hlsearch = true
set.incsearch = true
set.smartcase = true
set.wildmode = 'longest:full,full'
set.splitbelow = true
set.splitright = true
set.wrap = false
set.scrolloff = 5
set.fileencoding = 'utf-8'
set.termguicolors = true
set.relativenumber = true
set.nu = true
set.cursorline = true
set.hlsearch = true
set.smartcase = true
set.incsearch = true
set.hidden = true
set.swapfile = false
set.backup = false
set.undodir = os.getenv('HOME') .. '/.vim/undodir'
set.undofile = true
set.scrolloff = 8
set.sidescrolloff = 8
set.signcolumn = "yes"
set.textwidth = 120
set.colorcolumn = "+1"
set.clipboard = 'unnamedplus' -- Use Linux system clipboard
